Barebone ItemActivity, DB Stuff, and update for git ignore
CMPUT301F23T12/finding-tory pull request #29
Opened 2023-11-08 17:08 UTC by Aakash1417

2023-11-08 18:46 UTC, parshva-s requested changes

2023-11-08 18:46 UTC, parshva-s commented on app/src/main/java/com/example/finding_tory/ItemView.java
> +                startActivity(editItemIntent);
This won't update item since it isn't getting result of after editing item. Would need to implement [onActivityResult()](https://developer.android.com/training/basics/intents/result) so edits are reflected.

2023-11-08 18:46 UTC, parshva-s commented on app/src/main/java/com/example/finding_tory/ItemView.java
> +                DeleteItemFragment().show(getSupportFragmentManager(), "DELETE_ITEM");
comment as there is no implementation for this
```suggestion
                // DeleteItemFragment().show(getSupportFragmentManager(), "DELETE_ITEM");
```

2023-11-09 04:43 UTC, t-mannan requested changes

2023-11-09 04:43 UTC, t-mannan commented on .gitignore
> +/.idea/assetWizardSettings.xml
Unnecessary.
```suggestion
```

2023-11-09 04:43 UTC, t-mannan commented on app/src/main/java/com/example/finding_tory/InventoryViewActivity.java
> +                System.out.println("b4");
You left in a print statement.
```suggestion

```

2023-11-09 04:43 UTC, t-mannan commented on app/src/main/java/com/example/finding_tory/Item.java
> +    public Item(Date purchaseDate, String description, String make, String model, Float estimatedValue, String comment, ArrayList<String> itemTags) {
We probably don't need this second constructor anymore now that serialNumber is a String. Also we may consider whether estimatedValue needs to be a Float (why can't it be a primitive float?). @parshva-s you wrote this, while it's fine if we keep this in it seems like it could be cleaned up.

2023-11-09 04:43 UTC, t-mannan commented on app/src/main/java/com/example/finding_tory/Item.java
> +        if (Float.parseFloat(estimatedValue) <= 0) return "Cannot have a negative expense cost";
This was probably a remnant of exp-book, but this should be "estimated value" and not "expense."

2023-11-09 04:43 UTC, t-mannan commented on app/src/main/java/com/example/finding_tory/ItemViewActivity.java
> +        setContentView(R.layout.activity_item_view);
We may want to set the title of the activity, because by default it's "finding-tory".
```suggestion
        setContentView(R.layout.activity_item_view);
        setTitle("View Item");
```

2023-11-09 05:28 UTC, t-mannan approved these changes

2023-11-09 05:29 UTC, parshva-s approved these changes

2023-11-09 05:29 UTC, merged